### PR TITLE
Frontend: Improve Error Boundary Coverage. Closes #978

### LINKED ISSUE #978: Enhancement: Improve Error Boundary coverage in major route sections
## Description
Currently, the GreedyBear frontend uses `Suspense` to handle loading states for lazy-loaded routes but lacks `ErrorBoundary` components. This means that if any component within a major route section (Dashboard, Feeds, or Sessions) throws a runtime error, it will cause the entire application to crash, leading to a poor user experience.

Adding Error Boundaries will:
1. Prevent full-app crashes by catching errors at the route level.
2. Allow showing a fallback UI (e.g., an error message with a "Retry" or "Go Home" button) while keeping the rest of the application (like the header/footer) functional.

## Target Sections
- **Dashboard** (`/dashboard`)
- **Feeds** (`/feeds`)
- **Sessions** (`/me/sessions`)

## Proposed Solution
1. Create a reusable `ErrorBoundary` wrapper component in `src/wrappers/`.
2. Wrap the lazy-loaded elements in `src/components/Routes.jsx` with this `ErrorBoundary`.
3. Implement a fallback UI that aligns with the existing design (using `reactstrap` and existing styles).

## Validation Plan
- Automated unit tests for the `ErrorBoundary` component.
- Manual verification by forcing errors in specific routes.

### PR DESCRIPTION
**Pull request by chauhan-varun**
# Description

This PR introduces improved error boundary coverage for the frontend application. It adds a reusable `ErrorBoundary` component and integrates it into major protected routes.

image
image

Key changes:
- **`ErrorBoundary.jsx`**: Created a reusable class component to catch runtime errors and display a fallback UI with "Reload" and "Home" options.
- **Full Route Protection**: Extended coverage to **all application routes** (Home, Dashboard, Feeds, Login, Register, Logout, etc.) to ensure complete application robustness.
- **Optimized Nesting**: Refactored `Routes.jsx` mapping logic to ensure `ErrorBoundary` wraps `Suspense`. This allows the application to catch both component runtime errors and chunk-loading failures (lazy-load errors).
- **Renamed Property**: Renamed the control flag to `withErrorBoundary` (from `hasErrorBoundary`) to avoid ambiguity with internal React Router v7 properties as suggested by the maintainer.
- **Unit Tests**: Implemented comprehensive tests in `ErrorBoundary.test.jsx` verifying error catching, fallback rendering, and console logging.

### Related issues

closes #978

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Chore (refactoring, dependency updates, CI/CD changes, code cleanup, docs-only changes).

# Checklist

### Formalities

- [x] I have read and understood the rules about [how to Contribute](https://intelowlproject.github.io/docs/GreedyBear/Contribute/) to this project.
- [x] I chose an appropriate title for the pull request in the form: `<feature name>. Closes #999`
- [x] My branch is based on `develop`.
- [x] The pull request is for the branch `develop`.
- [x] I have reviewed and verified any LLM-generated code included in this PR.

### Docs and tests

- [x] I documented my code changes with docstrings and/or comments.
- [ ] I have checked if my changes affect user-facing behavior that is described in the [docs](https://intelowlproject.github.io/docs/GreedyBear/Introduction/). If so, I also created a pull request in the [docs repository](https://github.com/intelowlproject/docs).
- [x] Linter (`Ruff`) gave 0 errors.
- [x] I have added tests for the feature/bug I solved.
- [x] All the tests gave 0 errors.

### GUI changes

- [ ] I have provided a screenshot of the result in the PR.
- [x] I have created new frontend tests for the new component or updated existing ones.

### CODE REVIEW

**Comment by chauhan-varun** [comment]
Hey @regulartim PR is ready for a review, 

 I noticed the current npm and pip installs are quite slow. Would you be open to migrating to pnpm and uv to speed up local development and Docker builds? I'm happy to handle the migration if you're interested!

**Comment by regulartim** [comment]
Hey @chauhan-varun ! 

> PR is ready for a review,

Will review it soon (might take a while). 

> I noticed the current npm and pip installs are quite slow. Would you be open to migrating to pnpm and uv to speed up local development and Docker builds? I'm happy to handle the migration if you're interested!

Good idea. I already have a local branch testing uv and bun, but pnpm might actually be a better fit. Will probably merge the change after the next release.

**Comment by chauhan-varun** [comment]
Thanks! Sounds good. Happy to wait for the review.

I’d be happy to help with the pnpm migration whenever you decide to move forward

File: frontend/src/components/Routes.jsx [hunk 1]
```diff
@@ -28,15 +29,24 @@ const publicRoutesLazy = [
   {
     path: "/dashboard",
     element: <Dashboard />,
+    hasErrorBoundary: true,
```
Comment (regulartim) [inline frontend/src/components/Routes.jsx]: There is a property in react router named `hasErrorBoundary`:
https://api.reactrouter.com/v7/interfaces/react-router.IndexRouteObject.html#haserrorboundary

So maybe it is more unambiguous to use a different name here? `withErrorBoundary`?

Comment (chauhan-varun) [reply frontend/src/components/Routes.jsx]: Initially I only focused on the main route sections (Dashboard, Feeds, and Sessions) mentioned in the issue, but wrapping all routes definitely makes the app more robust. I’ll update the PR to add Error Boundary coverage for all routes. Also, I’ll remove the flag to avoid the name conflict
