### PR TITLE
Redundant API fetching fix. Closes #1135

### LINKED ISSUE #1135: [Frontend] Redundant API Fetching (Data Overlap)
Caught something while looking at the dashboard components - we're hitting `IOC_ATTACKER_COUNTRIES_URI` twice on every refresh. 

Right now, `AttackOriginMap.jsx` and `AttackOriginCountriesChart` (in `charts.jsx`) are both listening to the `useTimePickerStore` range. When that range updates, they both fire off their own axios request to the exact same endpoint with the exact same params. 

Found it here:
- `AttackOriginMap.jsx` (lines 78-80) triggers a request for the map data.
- `charts.jsx` (lines 149-151) triggers an identical request for the top countries list.

It’s not breaking anything visually yet, but we're basically doubling the backend load for that specific stat for no reason. Plus, if one request fails while the other works, we'll end up with a map and a list that don't match up.

Instead of having them fetch independently, we should probably pull the fetching logic out into a shared hook or just have a single provider that fetches the data once and passes it down. This kind of redundancy is a good case for why the dashboard needs a more modular data-fetching setup.

### PR DESCRIPTION
**Pull request by chauhan-varun**
# Description

This PR resolves the redundant API fetching issue in the GreedyBear dashboard by centralizing data management for the `attacker-countries` endpoint into a shared Zustand store. Previously, both the World Map and the Top Countries chart would trigger identical, simultaneous requests for the same time range.

Key improvements:
- **Centralized Store**: Created `useAttackerCountriesStore` to manage all data fetching and normalization for country statistics.
- **De-duplication**: Both components now consume from the same store, resulting in exactly one API call per range change instead of two.
- **Caching**: Successfully fetched data is cached in the store, preventing redundant network requests when switching back to a previously loaded time range.
- **Race Condition Handling**: Implemented `AbortController` to automatically cancel stale in-flight requests when a user rapidly switches between time ranges.
- **Stability**: Added defensive data validation and robust error rendering to handle malformed API responses or network failures gracefully.

### Related issues

Closes #1135

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Chore (refactoring, dependency updates, CI/CD changes, code cleanup, docs-only changes).

# Checklist

### Formalities

- [x] I have read and understood the rules about [how to Contribute](https://intelowlproject.github.io/docs/GreedyBear/Contribute/) to this project.
- [x] I chose an appropriate title for the pull request in the form: `Redundant API fetching fix. Closes #1135`
- [x] My branch is based on `develop`.
- [x] The pull request is for the branch `develop`.
- [x] I have reviewed and verified any LLM-generated code included in this PR.

### Docs and tests

- [x] I documented my code changes with docstrings and/or comments.
- [x] I have checked if my changes affect user-facing behavior that is described in the [docs](https://intelowlproject.github.io/docs/GreedyBear/Introduction/). If so, I also created a pull request in the [docs repository](https://github.com/intelowlproject/docs).
- [x] Linter (`Ruff`) gave 0 errors.
- [x] I have added tests for the feature/bug I solved.
- [x] All the tests gave 0 errors.

### GUI changes

- [x] I have provided a screenshot of the result in the PR.
- [ ] I have created new frontend tests for the new component or updated existing ones.

### CODE REVIEW

**Comment by chauhan-varun** [comment]
Hey @regulartim, could you review this PR when you get a chance?

I also touched [register.test.jsx](https://github.com/intelowlproject/GreedyBear/pull/1144/changes#diff-f9be706669cc8120c063801e9d1387bbd1d96ef618bd88f43487bc5d40f2f911) to increase the timeout a bit, because that test was flaky in the full coverage run and was still failing CI even after the main fix

File: frontend/src/stores/useAttackerCountriesStore.jsx [hunk 1]
```diff
@@ -0,0 +1,103 @@
+import axios from "axios";
+import { create } from "zustand";
+import { IOC_ATTACKER_COUNTRIES_URI } from "../constants/api";
+
+const NAME_FIXES = {
```
Comment (armoredvortex) [inline frontend/src/stores/useAttackerCountriesStore.jsx:6]: The comment explaining why these fixes exist should be present here also so that the intent is not lost.

File: frontend/src/stores/useAttackerCountriesStore.jsx [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+  loading: false,
+  error: null,
+  lastRange: null,
+  currentController: null,
+
+  fetchData: async (range) => {
+    const rangeStr = JSON.stringify(range);
+    if (get().lastRange === rangeStr && !get().error) return;
+
+    if (get().loading && get().lastRange === rangeStr) return;
```
Comment (armoredvortex) [inline frontend/src/stores/useAttackerCountriesStore.jsx]: the 2nd condition seems redundant, if loading were to be `false` the line above would've already returned.

File: frontend/src/components/dashboard/AttackOriginMap.jsx [hunk 3]
```diff
@@ -149,7 +106,9 @@ export default function AttackOriginMap() {
         className="d-flex justify-content-center align-items-center text-muted"
         style={{ minHeight: 200 }}
       >
-        {error}
+        {typeof error === "string"
```
Comment (armoredvortex) [inline frontend/src/components/dashboard/AttackOriginMap.jsx]: this is inside `if (error)` block so `error?` branch is dead code.

**Comment by chauhan-varun** [comment]
Hey @armoredvortex Good catch, you were right. I removed the redundant error fallback and simplified the error rendering in both dashboard components

**Comment by armoredvortex** [comment]
> Hey @armoredvortex Good catch, you were right. I removed the redundant error fallback and simplified the error rendering in both dashboard components

@chauhan-varun, please correct me if i'm wrong but, this still looks flawed.
1) error can only be a string inside that block (as per current implementation) so typeof error == "string" check is not required.
2) in the other branch which is never reached, you're using `error.message` which is non existent. where does that come from?

**Comment by chauhan-varun** [comment]
Ahh yeah, you’re right. Fixed it now just rendering {error} directly, Thanks for the review @armoredvortex

File: frontend/tests/components/auth/Register.test.jsx
Comment (regulartim) [inline frontend/tests/components/auth/Register.test.jsx:1]: > I also touched [register.test.jsx](https://github.com/intelowlproject/GreedyBear/pull/1144/changes#diff-f9be706669cc8120c063801e9d1387bbd1d96ef618bd88f43487bc5d40f2f911) to increase the timeout a bit, because that test was flaky in the full coverage run and was still failing CI even after the main fix

That's fine for now, but it does not really change the fact that the test is flaky, right? Should we maybe change the way we test here? If so, would you please open an issue for that?

**Comment by regulartim** [comment]
@armoredvortex Also, thanks for the review! :)

File: frontend/tests/components/auth/Register.test.jsx
Comment (chauhan-varun) [reply frontend/tests/components/auth/Register.test.jsx:1]: Yeah you're right, the timeout is just a band-aid. Opened #1148 for it
The main problems are leaked `localStorage` between tests and `userEvent.type` being too slow
