### PR TITLE
Fix blank page caused by upgrade to vite 8. Closes #1126

### LINKED ISSUE #1126: Login page renders empty
After upgrading to vite 8 (which uses Rolldown) opening the login page results in a empty screen. It seems that the new vite version is causing `useSearchParam` and `useTitle` to be undefined at runtime.

### PR DESCRIPTION
**Pull request by regulartim**
# Description

This changes all react-use/lib/ imports to react-use/esm/. No functional change but this is required for compatibility with vite 8+.

### Related issues

Closes #1126 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Chore (refactoring, dependency updates, CI/CD changes, code cleanup, docs-only changes).

# Checklist

Please complete this checklist carefully. It helps guide your contribution and lets maintainers verify that all requirements are met.

### Formalities

- [x] I have read and understood the rules about [how to Contribute](https://intelowlproject.github.io/docs/GreedyBear/Contribute/) to this project.
- [x] I chose an appropriate title for the pull request in the form: `<feature name>. Closes #999`
- [x] My branch is based on `develop`.
- [x] The pull request is for the branch `develop`.
- [x] I have reviewed and verified any LLM-generated code included in this PR.

### Docs and tests

- [ ] I documented my code changes with docstrings and/or comments.
- [x] I have checked if my changes affect user-facing behavior that is described in the [docs](https://intelowlproject.github.io/docs/GreedyBear/Introduction/). If so, I also created a pull request in the [docs repository](https://github.com/intelowlproject/docs).
- [x] Linter (`Ruff`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowlproject.github.io/docs/GreedyBear/Contribute/#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved.
- [ ] All the tests gave 0 errors.

### GUI changes

Ignore this section if you did not make any changes to the GUI.

- [ ] I have provided a screenshot of the result in the PR.
- [ ] I have created new frontend tests for the new component or updated existing ones.
  
# Review process

- We encourage you to create a draft PR first, even when your changes are incomplete. This way you refine your code while we can track your progress and actively review and help.
- If you think your draft PR is ready to be reviewed by the maintainers, click the corresponding button. Your draft PR will become a real PR.
- If your changes decrease the overall tests coverage (you will know after the Codecov CI job is done), you should add the required tests to fix the problem.
- Every time you make changes to the PR and you think the work is done, you should explicitly ask for a review. After receiving a "change request", address the feedback and click "request re-review" next to the reviewer's profile picture at the top right.

### CODE REVIEW

**Comment by regulartim** [comment]
@armoredvortex Would you please take a look?

File: frontend/src/wrappers/ifAuthRedirectGuard.jsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import React from "react";
 import PropTypes from "prop-types";
 import { Navigate } from "react-router-dom";
-import useSearchParam from "react-use/lib/useSearchParam";
+import useSearchParam from "react-use/esm/useSearchParam";
```
Comment (armoredvortex) [inline frontend/src/wrappers/ifAuthRedirectGuard.jsx]: Importing from library internals is not right.
Instead, 
```js
import useSearchParam from "react-use";
```

File: frontend/tests/wrapper/IfAuthRedirectGuard.test.jsx [hunk 2]
```diff
@@ -11,7 +11,7 @@ vi.mock("../../src/stores", () => ({
 }));
 
 const mockUseSearchParam = vi.fn();
-vi.mock("react-use/lib/useSearchParam", () => ({
+vi.mock("react-use/esm/useSearchParam", () => ({
```
Comment (armoredvortex) [inline frontend/tests/wrapper/IfAuthRedirectGuard.test.jsx]: this should only be 
```js
vi.mock("react-use/useSearchParam", () ...
```
now

Comment (regulartim) [reply frontend/tests/wrapper/IfAuthRedirectGuard.test.jsx]: Almost! This was the solution:
```js
vi.mock("react-use", () => ({
  useSearchParam: () => mockUseSearchParam(),
}));
```

Comment (armoredvortex) [reply frontend/tests/wrapper/IfAuthRedirectGuard.test.jsx]: yes, my bad!

**Comment by regulartim** [comment]
Thanks @armoredvortex ! Glad I asked you! :D
