### PR TITLE
fix qcluster permission error on mlmodels volume. Closes #1176

### LINKED ISSUE #1176: Model training fails due to permission error
After the merge of #1168  , model training fails. The job does not have permission to read the training data anymore.

Logs:
```
2026-04-02 00:00:27,299 - greedybear.cronjobs.base.TrainModels - execute - ERROR - [Errno 13] Permission denied: '/opt/deploy/greedybear/mlmodels/training_data.json'
Traceback (most recent call last):
  File "/opt/deploy/greedybear/greedybear/cronjobs/scoring/scoring_jobs.py", line 138, in run
    s.train(training_df)
    ~~~~~~~^^^^^^^^^^^^^
  File "/opt/deploy/greedybear/greedybear/cronjobs/scoring/random_forest.py", line 64, in train
    self.save()
    ~~~~~~~~~^^
  File "/opt/deploy/greedybear/greedybear/cronjobs/scoring/ml_model.py", line 73, in save
    raise exc
  File "/opt/deploy/greedybear/greedybear/cronjobs/scoring/ml_model.py", line 69, in save
    storage.delete(self.file_name)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/core/files/storage/filesystem.py", line 184, in delete
    os.remove(name)
    ~~~~~~~~~^^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/deploy/greedybear/mlmodels/random_forest_classifier'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/deploy/greedybear/greedybear/cronjobs/base.py", line 19, in execute
    self.run()
    ~~~~~~~~^^
  File "/opt/deploy/greedybear/greedybear/cronjobs/scoring/scoring_jobs.py", line 140, in run
    self.save_training_data()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/deploy/greedybear/greedybear/cronjobs/scoring/scoring_jobs.py", line 61, in save_training_data
    raise exc
  File "/opt/deploy/greedybear/greedybear/cronjobs/scoring/scoring_jobs.py", line 54, in save_training_data
    self.storage.delete(TRAINING_DATA_FILENAME)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/core/files/storage/filesystem.py", line 184, in delete
    os.remove(name)
    ~~~~~~~~~^^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/deploy/greedybear/mlmodels/training_data.json'
```

Permissions:
```
❯ docker exec greedybear_qcluster ls -la /opt/deploy/greedybear/mlmodels/                                                                                                                 
total 2900                                                                                                                                                                                
drwxr-xr-x 2     2000       82    4096 Apr  1 00:00 .                                                                                                                                     
drwxr-xr-x 1 www-data www-data    4096 Apr  2 05:55 ..                                                                                                                                    
-rw-r--r-- 1     2000       82 1171433 Apr  1 00:00 random_forest_classifier                                                                                                              
-rw-r--r-- 1     2000       82  380817 Apr  1 00:00 random_forest_regressor                                                                                                               
-rw-r--r-- 1     2000       82 1408871 Apr  1 00:00 training_data.json  
```

### PR DESCRIPTION
**Pull request by manik3160**
# Description

This PR fixes a `PermissionError` that occurs during `qcluster` model training after merging #1168.

Previously, `usermod -u 2000 www-data` mapped the `www-data` user to UID 2000 in the Docker container, and the `qcluster` service ran under this config. PR #1168 removed this mapping but kept the service running under the default `www-data` user (UID 33). Because Docker heavily persists the associated `mlmodels` volume data from prior executions, existing files remained owned by the stale UID 2000, denying the new `www-data` UID the ability to read or delete training data files and crashing model jobs.

Key changes:
- **New Entrypoint Script (`docker/entrypoint_qcluster.sh`)**: Added a targeted entrypoint for `qcluster` that explicitly runs `chown -R www-data:www-data` on the `/opt/deploy/greedybear/mlmodels` directory to ensure permissions align. Privileges are then securely dropped back to `www-data` via `gosu`, maintaining the established pattern used for `gunicorn`.
- **`docker-compose` Configuration Update**: Replaced `user: "www-data:www-data"` in `docker/default.yml` with the newly established `entrypoint_qcluster.sh` start sequence.

Before
image

After
image

### Related issues

Closes #1176

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Chore (refactoring, dependency updates, CI/CD changes, code cleanup, docs-only changes).

# Checklist

Please complete this checklist carefully. It helps guide your contribution and lets maintainers verify that all requirements are met.

### Formalities

- [x] I have read and understood the rules about [how to Contribute](https://intelowlproject.github.io/docs/GreedyBear/Contribute/) to this project.
- [x] I chose an appropriate title for the pull request in the form: `fix qcluster permission error on mlmodels volume. Closes #1176`
- [x] My branch is based on `develop`.
- [x] The pull request is for the branch `develop`.
- [x] I have reviewed and verified any LLM-generated code included in this PR.

### Docs and tests

- [x] I documented my code changes with docstrings and/or comments.
- [x] I have checked if my changes affect user-facing behavior that is described in the [docs](https://intelowlproject.github.io/docs/GreedyBear/Introduction/). If so, I also created a pull request in the [docs repository](https://github.com/intelowlproject/docs).
- [x] Linter (`Ruff`) gave 0 errors. If you have correctly installed [pre-commit](https://intelowlproject.github.io/docs/GreedyBear/Contribute/#how-to-start-setup-project-and-development-instance), it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved. 
- [x] All the tests gave 0 errors.

### CODE REVIEW

File: docker/entrypoint_qcluster.sh [hunk 1]
```diff
@@ -0,0 +1,6 @@
+#!/bin/bash
+
+# Fix mlmodels ownership (volumes may retain files owned by a previous UID)
+chown -R www-data:www-data /opt/deploy/greedybear/mlmodels
```
Comment (manik3160) [inline docker/entrypoint_qcluster.sh:4]: Should we optimize it to avoid recursive chown on every startup (for large mlmodels volumes), or is this  acceptable ?

**Comment by manik3160** [comment]
Hey @regulartim, I’ve addressed the changes. Would appreciate your feedback when you get a chance.

File: docker/entrypoint_qcluster.sh (hunk 1 above)
Comment (regulartim) [reply docker/entrypoint_qcluster.sh:4]: Totally acceptable. :)

**Review by regulartim — CHANGES_REQUESTED** [review]
Hey @manik3160 ! Loogs good, thanks! One thing: The gunicorn entrypoint skips gosu when DJANGO_TEST_SERVER=True (for hot-reload as root). The new qcluster entrypoint always uses gosu. I think I would prefer if we could also skip it here.

**Comment by manik3160** [comment]
Done! I've updated the entrypoint to skip gosu in dev mode to match the gunicorn logic.

**Review by regulartim — APPROVED** [review]
Nice, thank you! :)
